### ISSUE TITLE
dokku-ish deploy?

### ISSUE THREAD

**Issue by fruitl00p** [wercker/step-heroku-deploy#17]
Since heroku and dokku (and derivatives like dokku-alt) share the same idea of heroku (just push to a git repo using a predefined deploy key with a set username) would it be possible to utilize this step as a base for a step-dokku-deploy ?

Since we're looking for a better integration with our dokku(alt) setup, this seemed the most logical place to start :)

**Comment by hatchan** [comment]
Currently this step is tightly integrated with Heroku. 

If you are looking at creating your own step, then you certainly can use this step as a base. Just remove the Heroku related code, and fill the holes with Dokku related code.

We currently have no concrete plans to create a dokku deploy step, but we're not excluding it either.

**Comment by fruitl00p** [comment]
Thanks, i've since then forked this, upated it, and pushed it to wercker for initial testing ;) (and have have found some difficiculties translating yml properties into environment variables :)

Again, Thnx!
